train_path: ../data/coco2014/trainvalno5k.txt
val_path: ../data/coco2014/5k.txt

classes: 80


img_size: 416
batch_size: 32
num_workers: 8

degrees: 0
translate: 0
scale: 0
shear: 0
hsv_h: 0.0138
hsv_s: 0.678
hsv_v: 0.36
giou: 3.54
cls: 37.4
cls_pw: 1.0
obj: 64.3
obj_pw: 1.0
iou_t: 0.2
fl_gamma: 0.0

cfg: yolov3.cfg

lr0: 0.01
momentum: 0.937
weight_decay: 0.0005
conf_thres: 0.1
iou_thres: 0.6
multi_label: true
weights: ../weights/darknet53.conv.74
freeze_layers: false

epochs: 300
save_model: ../weights/yolov3m

seed: 123
gpu_index: 1